

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsi3tlQfAKBJJTYvZlfvDzEK7VipmwF3U',
    appId: '1:387034191563:android:a788b0618c9baba86b2d4e',
    messagingSenderId: '387034191563',
    projectId: 'practice-auth-1dfd8',
    storageBucket: 'practice-auth-1dfd8.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDWx2ufdyTfxvvacaX7BHlWVqQLlW63-_g',
  //   appId: '1:129444134575:ios:dca750c3eff5b99aa79e5a',
  //   messagingSenderId: '129444134575',
  //   projectId: 'ourreview-8474c',
  //   storageBucket: 'ourreview-8474c.appspot.com',
  //   // androidClientId: '314482240926-albb7h8ge1pi9jp8qpa4lqq73g132jar.apps.googleusercontent.com',
  //   // iosClientId: '314482240926-mcjqlpnk0n7k3ljql71dbmdfc019ac2r.apps.googleusercontent.com',
  //   iosBundleId: 'com.ourreview.app',
  // );
}
